$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    dots: false,
    responsive:{
        0:{
            items:1
        },
        320:{
            items:2.5
        },
        600:{
            items:3.5
        },
        1000:{
            items:4.5
        }
    }
})
